### ISSUE TITLE
[BUG] H4 to H6 in preview mode doesn't work

### ISSUE THREAD

**Issue by playANDcode** [crashmoney/obsidian-typewriter#1]
## Describe the bug
Having a word with Header 4 to 6 in preview mode shows no effect at all. 

This is an issue for compatability reasons since a lot of themes especially the top themes (Solarized, Atom etc..) in obsidian uses the ability of H4 to H6.

**Comment by crashmoney** [comment]
Hi, thanks for catching this bug. I just pushed an update that should fix this bug. H4, H5 and H6 now have bigger font sizes and are bolder. Let me know whether it works!
