### ISSUE TITLE
[FEATURE REQUEST] More obvious bold font

### ISSUE THREAD

**Issue by xinyi-li7** [crashmoney/obsidian-typewriter#13]
## Describe your feature request
Is it related to a problem, or an enhancement? Please describe clearly and concisely.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/69008042/165453212-8031674c-a24d-4d1c-8911-9b529ae553d1.png">
Here I changed the font-weight for bold as 1000, but still, as you could see in the picture, it is not obvious. 

## Proposed Solution
I want to make the bold fonts more obvious or at least we could customize it.

**Comment by crashmoney** [comment]
Closed #13 as completed.
