### ISSUE TITLE
[FEATURE REQUEST] - More visible checkboxes for tasks?

### ISSUE THREAD

**Issue by salil-p** [crashmoney/obsidian-typewriter#14]
## Describe your feature request
Love the theme, thanks! Minor suggestion though. The checkbox for todos/tasks is barely visible if I open a file in the sidebar. The main pane is better than the sidebar, but even there, the checkbox is not as dark as it should be.

Also, checkboxes are typically square. Radio-buttons are rounded. Possible to make the checkboxes square instead of round, for consistency?

## Proposed Solution
Above...

## Additional Context
Image is from the main pane. Sidebar checkboxes looks even more faint. 
![image](https://user-images.githubusercontent.com/1467808/169862812-ccc34adf-1e28-465a-b2df-7afe7470c9c5.png)

**Comment by salil-p** [comment]
Checkbox in sidebar:
![Screen Shot 2022-05-23 at 12 16 35 PM](https://user-images.githubusercontent.com/1467808/169864039-a644240d-397a-426b-a50b-c592fce9681f.png)

**Comment by salil-p** [comment]
This is with a light theme, btw.

**Comment by crashmoney** [comment]
I've changed the checkbox color slightly – it should be darker now. Could you update the theme and let me know whether it works for you? Thanks!

**Comment by crashmoney** [comment]
Closed #14 as completed.
