### ISSUE TITLE
[BUG] Bold font not displaying properly in dark mode

### ISSUE THREAD

**Issue by ironhak** [crashmoney/obsidian-typewriter#15]
## Describe the bug
With dark mode reading view does not display bold text.

## To Reproduce
Write something bold in live-preview or source mode:
![image](https://user-images.githubusercontent.com/62611612/175271970-4be4b0e0-9a89-46fc-a783-c029a5f8c74b.png)
Then switch to reading mode:
![image](https://user-images.githubusercontent.com/62611612/175272102-7b5993f0-f2de-47e6-85d0-52da64b76465.png)

## Suggestions/Workarounds
I'm not a coder and I've no knowledge about CSS so I can't give any suggestion. Tough I would like to have all font and styles of live-preview mode into reading mode, I would appreciate if someone can tell me how to do it. 

Hope you resolve this bug, thank's for this amazing theme.

**Comment by crashmoney** [comment]
Closed #15 as completed.
