### ISSUE TITLE
Editor Font not displaying correctly

### ISSUE THREAD

**Issue by anitaschaefer** [crashmoney/obsidian-typewriter#16]
I just installed the theme and all fonts seem to work (sidebar, settings, etc.) except for the editor (edit mode and preview). I have installed the fonts used after that, restarted Obsidian, restarted the PC, reinstalled the theme but nothing works. Do you have any advice on how to fix this?

Edit: I have Obsidian v.0.14.15

**Comment by crashmoney** [comment]
The editor font should now displays correctly in the latest version of Obsidian (v1.0.0) using `theme.css` 👍🏻
