### ISSUE TITLE
[BUG] Heading sizes aren't displayed from live preview mode

### ISSUE THREAD

**Issue by galderna** [crashmoney/obsidian-typewriter#17]
## Describe the bug
All headings from h1 to h6 display the same size in live preview mode, and their default size in reading mode.

## To Reproduce
1. Write h1, h2, h3, etc. headings 

## Information
 - OS: [e.g. iOS] Mac OS X 10.14.6 (Mojave)
 - Obsidian (recent manual update): Version 0.15.9 (installer 0.15.8)
 - Obsidian-typewriter version: the last one available as today. 

Add other context about the problem here. (Please make sure you've updated the theme before opening an issue.)

## Suggestions/Workarounds
Add any suggestions/workarounds on how to resolve the issue here.
Don't know much about CSS but this time I haven't seen defined the --h1-live-preview, --h2-live-preview, etc. in the typewriter.css file.

Thank you.

**Comment by sidshin** [comment]
Please fix this issue. I love your theme but cannot use now due to this issue.

**Comment by sidshin** [comment]
found the problem. put } into line 425. This would fix the heading issue
