### ISSUE TITLE
file menu design changed?

### ISSUE THREAD

**Issue by fightme-cmd** [crashmoney/obsidian-typewriter#18]
My file menu using this theme has changed. 
Top image is what it was (what I want) and below is what it is now.
Is there a way for me to keep the original - the dash of colour throws of the minimal theme and keeps catching my eye.

![image](https://user-images.githubusercontent.com/80396935/186401781-f76ec0c2-b8af-42fe-920a-c2b445aa0e69.png)

![image](https://user-images.githubusercontent.com/80396935/186401813-07dd00a5-8a8a-4bbf-a854-ace8d287434f.png)

**Comment by crashmoney** [comment]
In v2.0.0, Typewriter follows Obsidian's default file menu design, which is closer to what you wanted (the previous file menu) 👍🏻
