### ISSUE TITLE
[QUESTION] How to disable highlight on the active line?

### ISSUE THREAD

**Issue by karolszk** [crashmoney/obsidian-typewriter#19]
Hello,

I am using obsidian-typewriter theme for two months or so but after the recent update I have noticed that active line is highlighted in notes window. It's not for me. Can I disable it?
Thank you.

**Comment by crashmoney** [comment]
@karolszk, the active line highlight is back in v2.1.0. If you use the Style Settings plugin, there should be an option to toggle this feature on/off 👍🏻
