### ISSUE TITLE
Unable to Move Window

### ISSUE THREAD

**Issue by niisakov** [crashmoney/obsidian-typewriter#2]
When using the Typewriter theme, the window is fixed i.e.,  I cannot position it anywhere on the screen, I can only resize or maximize the view.  Is this intended and if so is there a way to get around this severe limitation?  Thanks.

**Comment by crashmoney** [comment]
Hi, I’m not quite sure what you mean by not being able to reposition the window. If you’re referring to the app window itself, you may want to report this bug to the Obsidian developers. Typewriter is a CSS theme that modifies only Obsidian’s appearance and doesn’t affect Obsidian’s core functionality.

If it’s a Typewriter-only issue (i.e., it persists after disabling all community plugins and/or CSS snippets), please provide steps to reproduce this bug - I haven’t run into anything like this in my use of the theme. Thank you in advance!

**Comment by niisakov** [comment]
I have disabled all community plugins and CSS snippets, restarted it multiple times, and each time I am unable to move the windows - yes, the app window itself i.e., holding down the left-mouse button (or equivalent on keyboard) and repositioning it.   This only happens when using the Typewriter theme.  When I switch to any other theme, or relaunch Obsidian w/ any other theme, I do not have this issue.

To reproduce, I am simply launching Obsidian either w/ the Typewriter theme already enabled, or another theme and then switching to the Typewriter theme.  Whenever I do this, the app window itself cannot be repositioned.  It can only be maximized or expanded via using the mouse to grab one of the corners and moving them i.e., like you would expand any app window.

**Comment by crashmoney** [comment]
Hi @niisakov, I tried the steps above and was able to reproduce the bug. The issue appears to have been with the titlebar styling. I've just pushed an update that should fix this – could you update the theme and let me know whether it works? Thanks for reporting this bug!

**Comment by niisakov** [comment]
Excellent!  Thank you @crashmoney; everything works as intended.  Thanks for resolving this soo quickly!

**Comment by crashmoney** [comment]
No problem :) Glad you enjoy the theme!
