### ISSUE TITLE
[BUG] Links are difficult too read because of bright green color

### ISSUE THREAD

**Issue by flarik** [crashmoney/obsidian-typewriter#20]
## Describe the bug
The Linked color is to bright, which makes it difficult to read

See screenshot below:

![Screenshot 2022-10-18 at 18 07 51](https://user-images.githubusercontent.com/194395/196484535-1afc9b2e-e3ce-4364-9b22-5f229aaba99a.png)

## To Reproduce
1. Open any file with a link

## Information
 - OS: MacOS Montery 12.6, iOS 15.6.1

## Suggestions
Darken the link color.

**Comment by crashmoney** [comment]
The link colour bug has been resolved in 6c2eea5af683bba9d9e0a1ea612f4462f7845624 👍🏻
