### ISSUE TITLE
Contextual menu transparency makes it hard to read.

### ISSUE THREAD

**Issue by vanTersec** [crashmoney/obsidian-typewriter#21]
![image](https://user-images.githubusercontent.com/3130920/196551738-0241a969-15f8-469f-bf39-bf08e39e7ada.png)

When the contextual menu is to appear over a block of text, the contextual menu is hard to read because it's translucent

**Comment by crashmoney** [comment]
Hi, I don't think I can reproduce this bug in the latest version. Could you please update Typewriter to v2.0.3 and see whether the issue persists? Thanks 👍🏻

**Comment by vanTersec** [comment]
Updated again today and the issue was gone.
