### ISSUE TITLE
Disable <Markdown formatting symbols are faded and shrunk>[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by SimiPixel** [crashmoney/obsidian-typewriter#22]
## Describe your feature request
It would be nice to disable the behaviour 
- *that Markdown formatting symbols are faded and shrunk.*

I personally can not really read it properly.

## Proposed Solution
Some setting / toggle / STRG+P Command to enable/disable this behaviour.

**Comment by crashmoney** [comment]
@SimiPixel, if you use the Style Settings plugin there should now be a toggle to turn this on/off. Could you try updating the theme and seeing whether it works? Thanks!

**Comment by SimiPixel** [comment]
Works perfectly. Thanks!
