### ISSUE TITLE
Monospace text not scaling

### ISSUE THREAD

**Issue by jscd** [crashmoney/obsidian-typewriter#24]
## Describe the bug
Monospace text does not scale with the rest of the document while using this theme.

Screenshot in source mode at minimum font size:
![image](https://user-images.githubusercontent.com/30761811/203399860-da9a848c-62e2-4a48-8b71-30066d5c63cc.png)

Screenshot in reading view at minimum font size:
![image](https://user-images.githubusercontent.com/30761811/203399883-3fbc16a0-078c-4685-b781-c569f0450a0b.png)

Screenshot in source mode at large font size:
![image](https://user-images.githubusercontent.com/30761811/203399938-1ca3ae15-dac0-4c83-aba8-52b3d7d658a7.png)

Screenshot in reading view at large font size:
![image](https://user-images.githubusercontent.com/30761811/203399952-662df276-10ba-4b61-9292-7a983c69306f.png)

For some reason, regardless of the font setting, the monospace font does not change size at all.

## To Reproduce
1. Have monospace text (using single or triple backticks).
2. Scale the document either using the "Font size" slider in Options->Appearance or by Ctrl+Scroll.

## Information
 - OS: Fedora
 - Obsidian Version: v1.0.3
 - No community plugins
 - All default appearance settings

**Comment by crashmoney** [comment]
Hi @jscd, could you try updating the theme to v2.1.1 and letting me know whether it works? Thanks!

**Comment by jscd** [comment]
Works perfectly now, thanks!
