### ISSUE TITLE
[BUG] Line highlight/Vim cursor is broken on Legacy Mode

### ISSUE THREAD

**Issue by RobertoGongora** [crashmoney/obsidian-typewriter#3]
## Describe the bug
I had to enable Legacy Mode to make the Typewriter scroll plugin work again, but the line highlight started to work very funky in the legacy editor.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/1845147/147215834-ef8ddac5-95b1-42a8-9f84-38c4244095ef.png">

https://user-images.githubusercontent.com/1845147/147216726-33eeabc7-4070-4867-bdbc-b0fdd1a5a693.mov

Apparently the vim cursor itself is the one that's broken, the highlighted line is correct but the vim cursor appears elsewhere.

## To Reproduce
1. Enable Vim Keybinds
2. Enable Legacy Mode
3. Move cursor around different headings
4. The highlighted line will move to the line below the heading, and this can be repeated several times and the highlight will keep moving down

If you switch to the default obsidian theme, the issue resolves itself.

## Information
 - OS: macOS Monterey
 - Version of Typewriter: Current (not sure how to see but I made sure to click Update on the Themes manager)

This only started happening after the recent Live Preview update.

## Workaround

As a workaround, I had to enable the Live Preview mode and use it in Source Mode (Because Live Preview is really bad imo), but this is not optimal because the heading styles are very different from what I was used to, and the line highlight is gone.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/1845147/147218241-90011fff-0282-4243-b709-96c524ee7c86.png">

**Comment by crashmoney** [comment]
I'm able to reproduce this bug. The issue appears to be with the CSS rules for headers. I've just pushed an update that fixed this in my testing. Could you update the theme and let me know whether it works? Thanks for reporting the bug!

**Comment by crashmoney** [comment]
Also, the line highlight now works in the new editor :)

**Comment by RobertoGongora** [comment]
I've just updated the theme and I can confirm that this now works perfectly in Legacy Mode and in Source Mode!

Thanks for the quick fix, your theme has really helped me focus on my writing and enjoy using Obsidian. I appreciate your hard work!
