### ISSUE TITLE
[FEATURE REQUEST] Edges in Graph View lack contrast/visibility.

### ISSUE THREAD

**Issue by 1b7** [crashmoney/obsidian-typewriter#33]
## Describe your feature request

Within the Graph view, I personally find it fairly hard to pick out the edges between nodes in the graph. This is especially true of Light Mode. I haven't had this with other themes so I don't believe this is a personal issue.

Here are some screenshots from my graph which I hope illustrate the issue (using a Link Thickness of 1.0 - I would normally use ~0.4 but initially increased this to try and make the lines clearer):

**Light Mode**
<img width="556" alt="image" src="https://user-images.githubusercontent.com/36208349/228555584-da782571-809b-4e72-84ed-cf2d0a762bfd.png">

**Dark Mode**
<img width="556" alt="image" src="https://user-images.githubusercontent.com/36208349/228555640-1429172d-4f31-402e-9843-56614966be2d.png">

## Proposed Solution
I think a really simple fix is just a change to the `.graph-view.color-line` class (mentioned [here](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/Graph+view+customization))

As a test, I added the following custom CSS snippet as a quick and hacky solution within my own Obsidian installation:
```css
.graph-view.color-line {
    color: #888;
}
``` 

And I think the result is significantly easier to see:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/36208349/228556467-18ee97d3-4181-4bc0-ba03-8754329448eb.png">

All other settings were kept the same between screenshots. `#888` was chosen very arbitrarily, I am not suggesting that this should be the colour used - and of course a different colour would need to be used for the dark mode.

(I would also note that using a darker colour allowed me to revert the link thickness back down to my original setting for a softer/less harsh appearance, without sacrificing visibility).

**Comment by crashmoney** [comment]
Hey @1b7! I've taken a look at your fix, and the class works perfectly. I've changed the color to `#c0c9ce` in light mode and `#6f7577` for dark mode, simply for aesthetics and readability when the lines cross over file names. I'll push this update first as a fix, but let me know what you think!

**Comment by 1b7** [comment]
That sounds great, thanks for implementing this!
