### ISSUE TITLE
Theme Colours Not Covering Windows Minimize, Maximize & Close 

### ISSUE THREAD

**Issue by NovaStorm775** [crashmoney/obsidian-typewriter#37]
In windows 11 the theme doesn't cover the 3 windows Icons on the top right of Obsidian, leaving them windows defult. Instead of following the Typewriter theme they background of Maxamze, Minimize & Close are Black/white depending on your windows theme settings.

**Comment by crashmoney** [comment]
Hey @NovaStorm775, thanks for reporting this bug. Unfortunately, I'm working on a Mac and don't have a Windows machine to reproduce this bug or test any fixes on. If you could take a screenshot and use the Inspector (`ctrl + shift + i`, then `ctrl + shift + c` to select the problematic buttons) to report the CSS classes associated with them, I could try and take a shot at it 😃 

In the meantime, I'll leave this issue open in case anyone on Windows can provide a PR fix.

**Comment by crashmoney** [comment]
Fix provided in #41.
