### ISSUE TITLE
[BUG] Highlighted headings become smaller

### ISSUE THREAD

**Issue by RobertoGongora** [crashmoney/obsidian-typewriter#4]
## Describe the bug
When you highlight a heaading (at least in Vim mode), the text becomes smaller.

<img width="243" alt="image" src="https://user-images.githubusercontent.com/1845147/147219001-619f6799-0055-433a-b36d-636161e61818.png">

## To Reproduce
1. Add a heading, doesnt matter which type (#, ##, ###)
2. Click and drag with the mouse, or press `v` and `w`

## Information
 - OS: macOS Monterey
 - Version of Typewriter: Latest available in the Theme Manager (not sure how to see it)

This happens only with the new Live Preview editor enabled, in Source mode.

**Comment by crashmoney** [comment]
Hi, I just pushed an update that should fix this. Could you update the theme and let me know whether it works? Thanks for reporting this bug!

**Comment by RobertoGongora** [comment]
Confirmed fixed! The only "issue" now is that the heading markers (#, ##, etc) still look different than they do in Legacy Mode, do you want me to open a new GH Issue for that?

Thanks for the quick fix!

**Comment by crashmoney** [comment]
Heading markers are now the same in both Legacy and Source Mode!
