### ISSUE TITLE
[BUG] Fold/collapse icons overlapping the text

### ISSUE THREAD

**Issue by JeFawk** [crashmoney/obsidian-typewriter#40]
## Describe the bug
First I would like to thank you for this free theme, it's great!

![image](https://github.com/crashmoney/obsidian-typewriter/assets/7268697/a5baded6-cb3e-41d0-b9f8-2bd6e30d8735)

## To Reproduce
1. Type something
2. Press enter and tab to create an indented text
3. Notice the top text has a collapse icon
4. Notice the overlap

## Information
 - OS: Windows

Add other context about the problem here. (Please make sure you've updated the theme before opening an issue.)

## Suggestions/Workarounds
Add any suggestions/workarounds on how to resolve the issue here.

**Comment by JeFawk** [comment]
If you select the text block that has the fold (select as in put the cursor on it) for some reason it shows correctly

![image](https://github.com/crashmoney/obsidian-typewriter/assets/7268697/0a2006ce-0497-43d7-be19-88e725af7b8b)

**Comment by JeFawk** [comment]
Also the cursor is offset.
![image](https://github.com/crashmoney/obsidian-typewriter/assets/7268697/125f661f-cb85-427f-bba2-5d17e055324f)

![image](https://github.com/crashmoney/obsidian-typewriter/assets/7268697/9715f95a-0cfc-43d0-a985-871708576df0)

This offset is just graphical as there is no space there, if i type something it puts a letter right next to the C, even though it would look like it would be letter _ C (_ from empty space)

**Comment by JeFawk** [comment]
This will fix it

```
div.cm-fold-indicator
{
  margin-right: 14px;
}
.markdown-source-view.mod-cm6 .cm-fold-indicator .collapse-indicator
{
  padding-right: 1rem;
  right: -1.25rem;
}
```

**Comment by crashmoney** [comment]
Hey, thanks for the issue and fix provided! This looks like a bug that's cropped up in newer versions of Obsidian.

I'll merge this into main once I get some spare time.

**Comment by crashmoney** [comment]
Strangely enough, I can't reproduce this issue on my machine. I've tried both indented normal text and bullets. It doesn't change the look at all, so I'll go on ahead and push this through main for anyone else experiencing the same bug 😄
