### ISSUE TITLE
[BUG] Unable to display bold 

### ISSUE THREAD

**Issue by froses** [crashmoney/obsidian-typewriter#45]
## Unable to display bold
If I mark a text as bold, the text is displayed as “normal” text. 

## To Reproduce
1. Edit an Obsidian note in Live Preview mode.
2. Mark some text as bold (i.e. **This is a bold text**) surounding it with `**`.
3. The text is displayed as normal text instead of bold text.
4. Change to reading mode: The issue persists.
5. Reproduce steps 1-3 but using italic. The text is displayed as expected.

## Information
 - OS: macOS Sonoma 14.4.1
 - Obsidian 1.6.0

Italic and monospaced works as expected.

**Comment by DaHunch** [comment]
yep - same - crossing fingers for an update soon!

**Comment by crashmoney** [comment]
Hi @froses and @DaHunch! I am unfortunately short on time at the moment, but hoping to resolve this rather high-priority bug ASAP. I also just noticed it yesterday all of a sudden – so not too sure what the issue could be yet.

Thanks for reporting!

**Comment by laserbat** [comment]
The issue is in [this line](https://github.com/crashmoney/obsidian-typewriter/blob/e3979971c7f240332609d25b0b7ec3c2230a0844/theme.css#L298C1-L298C22). Simply removing this line fixes the issue.

This is because `--font-normal` should define normal font weight, not font size. In the inspector you can see how it's used by Obsidian:

```
  /* Font weights */
  --font-weight: var(--font-normal);
  --font-thin: 100;
  --font-extralight: 200;
  --font-light: 300;
  --font-normal: 400;
  --font-medium: 500;
  --font-semibold: 600;
  --font-bold: 700;
  --font-extrabold: 800;
  --font-black: 900;
```

and then

```
b,
strong {
  font-weight: calc(var(--font-weight) + var(--bold-modifier));
  color: var(--bold-color);
}
```

**Comment by froses** [comment]
Hi, Olga,

It works for me. 

Thanks a lot!

FRA

**Comment by crashmoney** [comment]
Hi @laserbat! Thanks for providing the fix. I've credited you accordingly in both the commit and release notes :)

@froses and @DaHunch, I've committed this into main and released it. The theme should now work as intended once you update 👍🏻

**Comment by DaHunch** [comment]
Thanks @crashmoney - all working well again. p,.s. I so love the theme you've created - it's not an overstatement to say that to me IT IS OBSIDIAN - ie. I doubt I'd have anything close to the kind of productive relationship I have with my knowledge & projects without your theme. So thank you - it's a joy.

**Comment by DaHunch** [comment]
Hey … 

…. still loving Tyepwriter!

You are obviously very talented at this. I was just wondering … if I was to commission you to write some CSS to make your beautiful theme look exactly the same whether I was in Live Preview, Reading View or working with Canvas files… would …. 

a) that be possible?

b) you be able to quote me how much you’d like as a reward!?  I was thinking I could send you an Amazon gift card or Buy You A Coffee or something or just PayPal you etc.!

I work 100% of the time in Live Preview, but whenever I transclude a note, or look at one in Canvas, it hurts my eyes too bad …

Thanks - look forward to hearing from you!

Patrick

**Comment by crashmoney** [comment]
Hi @DaHunch! I just saw this while configuring some GitHub stuff to, yes, add a long-overdue [Ko-Fi](https://ko-fi/crashmoney7) to this project. Somehow, I didn't get notified by email about this comment. So, first of all, apologies for the late reply.

It's definitely one of my goals, but unfortunately I'm at a high-pressure point of my life right now. I'll have a lot more bandwidth for Typewriter around the end of this year to end of next year – unfortunately quite a long wait 😅

I'm thinking of opening a dev branch to get started if/when I can – someone else has also brought this up in #38. I'll copy my response from there over:

> ... if it's occurring in Obsidian's default theme, it's likely an issue with the app rather than Typewriter itself (and thus not something I can fix). You can file a feature request/bug report over on the Obsidian forums if that's the case :)

Regardless, I do agree it gets a bit jarring and I want to try and reduce the visual differences where I can.

Could I trouble you to list which design elements you'd like to see fixed (or at least mitigated within my power)?

Thanks so much!
