### ISSUE TITLE
[BUG] Banner plugin don't open icon

### ISSUE THREAD

**Issue by danebace** [crashmoney/obsidian-typewriter#5]
## Describe the bug
Just push command pallet and right "banner" and you see it
In view mode/Preview mode the Icon banner don't appear in this theme.

What you see: https://i.imgur.com/FBPTDBe.png
What you should see (other theme): https://i.imgur.com/3aRGKv7.png

## To Reproduce
1. Install banner plugin
2. on a note push command pallet and type "banner" 
3. select the "insert icon" option and choose one

## Information
 - OS: Linux Mint Ulyana 20
 

I updated the theme.
It doesn't happen in other themes.

## Suggestions/Workarounds
No idea..

P.S.: Your theme is by far the best! Please don't leave it

**Comment by crashmoney** [comment]
I just pushed an update that fixes this. Can you update the theme and let me know whether it works? Thanks for reporting this bug!

**Comment by danebace** [comment]
Hey! Unfurtunatly it stills not working, at least in my linux version. I update the plugin and restart obsidian without sucess.. Tks!

**Comment by crashmoney** [comment]
By ‘updating the plugin’ do you mean theme? I can no longer reproduce the bug after the last update.

**Comment by danebace** [comment]
Sorry. You are right. I updated the banner, not the theme ;)

crashmoney ***@***.***> escreveu no dia terça, 18/01/2022
à(s) 23:27:
