### ISSUE TITLE
[BUG] Appearance of some elements is back to the default theme

### ISSUE THREAD

**Issue by EDdeVries1** [crashmoney/obsidian-typewriter#6]
## Describe the bug
When updating the obsidian-typewriter theme after the new obsidian update, several formatting items are back to the default theme. These include Blocknotes, Task lists and Math. I have not checked other formatting items.

## To Reproduce
Steps to reproduce the behavior for 'Blocknotes':
1. Open New File
2. Switch to editing view
2. type '>Test'
3. switch to reading view

## Information
 - OS: Windows 11 Home
 - Obsidian: v.0.13.19
 - Typewriter: v1.0.21

**Comment by crashmoney** [comment]
I'm able to reproduce this bug and just pushed an update fixing this. Can you try updating the theme? Thanks!

**Comment by EDdeVries1** [comment]
I updated the theme and its working again, thank you!
