### ISSUE TITLE
Greater differentiation of heading sizes in Reading view [FEATURE REQUEST] 

### ISSUE THREAD

**Issue by ryadaj** [crashmoney/obsidian-typewriter#8]
## Describe your feature request
I was thinking it might be nice to have a greater differentiation in the heading sizes in reading view, particularly levels 1–3. It would make quick scanning documents a little easier.
![Screen Shot 2022-01-25 at 12 58 38](https://user-images.githubusercontent.com/82765301/151033514-bd6f4b4a-0b74-4ebb-a775-f0074e1825d3.png)

**Comment by crashmoney** [comment]
I just pushed an update fixing this. Could you try updating the theme and letting me know whether it works? Thanks!
