### ISSUE TITLE
right sidebar nav buttons should wrap [FEATURE REQUEST] 

### ISSUE THREAD

**Issue by avh4** [crashmoney/obsidian-typewriter#9]
## Describe your feature request

I have several plugins installed that add panels to the right sidebar (specifically, Calendar, Breadcrumbs, and Advanced Tables).  That's 9 nav button icons in total, and if the sidebar is too narrow, some of the buttons can't be seen and are unusable.

Note that the default Obsidian theme has this same problem, but some other themes (like https://github.com/nikbrunner/obsidian-deep-work-theme) have fixed it so that the buttons will wrap so they are all always visible.

## Proposed Solution

Make the sidebar nav icons wrap.

The base of the change would be:
```css
.workspace-tab-container-inner {
  flex-wrap: wrap;
}
.workspace-tab-header-container {
  height: auto;
}
```
but then additional small changes would need to be made to the design to deal with `workspace-tab-container-before` and `workspace-tab-container-after` which currently add some rounded edges to the active button.

## Additional Context

Current: (only the first 5 buttons are visible)
<img width="216" alt="Screen Shot 2022-02-18 at 11 32 08 PM" src="https://user-images.githubusercontent.com/1222/154791569-be1151f1-99d5-43cc-b6c3-0d7f6121cb97.png">

Example when using "nikbrunner/obsidian-deep-work-theme": (all buttons are visible)
<img width="220" alt="Screen Shot 2022-02-18 at 11 31 43 PM" src="https://user-images.githubusercontent.com/1222/154791589-0ab19150-3e9c-46eb-83bd-49e1b3eb3b4e.png">

**Comment by crashmoney** [comment]
This feature has been added in the latest theme release. Thanks for the FR!
